sudo: required
language: generic
services: 
  - docker
before_install: 
  - echo "start Creating an image with dockerfile"
  - docker build -t junho/build_react_app -f Dockerfile.dev .

script:
  - docker run -e CI=true junho/build_react_app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket-name: "elasticbeanstalk-ap-northeast-2-511098918467"
  bucket-path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

