--- 
after_success: 
  - "echo \"Test Success wow\""
before_install: 
  - "echo \"start Creating an image with dockerfile\""
  - "docker build -t junho/build_react_app -f Dockerfile.dev"
language: generic
script: 
  - "docker run -e CI=true junho/build_react_app npm run test -- --coverage"
services: 
  - docker
sudo: required
